#spring.application.name=OSApiApplication

spring.datasource.url=jdbc:mysql://172.16.0.30/ldb_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=ldb
spring.datasource.password=gmSenai